name: Release 

on: workflow_dispatch

jobs:
  github_release:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Tag commit and release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v0.9.1
        name: GitMagic v0.9.1
        bodyFile: ./docs/release_notes/v0.9.1.md
